config/routes.rb
Rails.application.routes.draw do
  get 'admin/new'
  get 'admin/index'
  get 'account/', to: 'pages#account'
  resources :availabilities
  resources :lessons
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges
  root to: "pages#home"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
    validates :start_time, uniqueness: true
    validates :end_time, uniqueness: true

    
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
    enum bookable: [:available, :unavailable]
    has_many :order_items
    validates :start_time, uniqueness: true
    
    after_initialize :set_default_bookable, :if => :new_record?

    def set_default_bookable
        self.bookable ||= :available
      end

    def date_readable
        start_time.strftime("%d/%m/%Y")
    end 

    def time_readable
        start_time.strftime("%l%P")
    end 

    def datetime_readable
        date_readable + " " + time_readable
    end

end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: [:active, :complete]
  scope :completed, -> { where(order_status: complete) }
  has_many :order_items
  belongs_to :user
  has_many :lessons, through: :order_items
  before_validation :set_order_status, on: :create
  before_save :update_subtotal


  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private
  def set_order_status
    self.order_status ||= :active
  end


  def update_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :lesson
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :lesson_present
  validate :order_present

  before_save :finalize
  before_save :set_lesson_status
  before_destroy :set_lesson_available

  def unit_price
    if persisted?
      self[:unit_price]
    else
      lesson.price
    end
  end

  private

  def lesson_present
    if lesson.nil?
      errors.add(:lesson, "is not valid.")
    end
  end

  def set_lesson_status
    lesson.unavailable!
  end 

  def set_lesson_available
    lesson.available!
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end  
  def finalize
    self[:unit_price] = unit_price
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # validation
  validates_presence_of :name
  validates_presence_of :address1
  validates_presence_of :address3
  validates_presence_of :county
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :phone,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 }
  has_many :orders
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def first_name
    self.name.split.first
  end
  
  def last_name
    self.name.split.last
  end 
  
end



 

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize_admin
  

  def index
  end

  private 
  def authorize_admin
    redirect_to root_path, alert: "Permissions denied" unless
     current_user.admin?
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end 

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
        @order = current_order 
        session[:order_id] = @order.id
        @amount = current_order.subtotal * 100
    end

    def thanks
    end 
    
    def create
      # Amount in cents
       total_in_cents =current_order.subtotal * 100
       @amount = total_in_cents.to_i
       @order = current_order
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => @order.id,
        :currency    => 'eur'
      )

      if charge["paid"] == true
        current_order.complete!
        session.delete(:order_id)
        @user = current_user
        UserNotifierMailer.send_lesson_email(@user).deliver
       end
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    private
   def order_params
    params.require(:order).permit(:id)
   end
   
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @lessons = Lesson.available
    @lesson_count = Lesson.available.count
    @order_item = current_order.order_items.new
    
  end

  def new
    @lesson = Lesson.new
  end 

  def create
    @lesson = Lesson.new(lesson_params)
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end 
    end

    def booked
      @lesson = Lesson.find(params[:id])
      @lesson.unavailable!
    end 

    def edit
      @lesson = Lesson.find(params[:id])
    end 

    def update
      @lesson = Lesson.find(params[:id])
      respond_to do |format|
          if @lesson.update(params.require(:portfolio).permit(:title, :subtitle, :body))
            format.html { redirect_to @lesson, notice: 'Record was successfully updated.' }
            format.json { render :index, status: :ok, location: @lesson }
          else
            format.html { render :edit }
            format.json { render json: @lesson.errors, status: :unprocessable_entity }
          end
        end
    end 
 
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
    
   end 

  def show
    @lesson = Lesson.find(params[:id])
    @order_item = current_order.order_items.new
  end 

  private
  def lesson_params
    params.require(:lesson).permit(:id, :duration, :price, :meeting_point, :date, :start_time)
  end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, :only => [:account]

  def home
  end

  def about
  end

  def account
    @lessons = user_orders
    @user = current_user
  end 

  private def user_orders
   OrderItem.select("lessons.start_time as lesson_start, order_items.order_id as order_id, orders.user_id as user_id, lessons.meeting_point as meeting_point, orders.order_status as status").joins(:order, :lesson).where('orders.user_id = ? AND orders.order_status = ?', current_user.id, 1)
  end 

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper

end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/index.html.erb
<div class="container-fluid">
<div class="row d-flex justify-content-center">
<section class="form-section col-md-4">
<h1>Admin Panel</h1>
<%= link_to "Create lessons", new_availability_path, class: 'btn btn-primary road-submit' %> 
<%= link_to "View current schedule", lessons_path, class: 'btn btn-primary road-submit' %> 
</section>
</div>
</div>

app/views/layouts/_cart_text.html.erb
<li class="nav-item"><span class='nav-link'>
  
<%= link_to  "Cart", cart_path, id: 'cart-link' %>  <%= link_to " ( #{number_to_currency current_order.subtotal, :unit => "€"} )", cart_path, id: "cart-link" %>  </span></li>

app/views/layouts/_footer.html.erb
<footer>
<div class="jumbotron main-footer" style="margin-bottom:0">
    <div class="row">
        <div class="col-12 col-md">
        <%= image_tag("cone.svg", :alt => "Open | Road Driving School", size: "24") %>

          <small class="d-block mb-3 text-muted"><br />© 2017-2018</small>
        </div>
        <div class="col-6 col-md">
       
        </div>
        <div class="col-6 col-md">
        </div>
        <div class="col-6 col-md">
          <h5></h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="/">Home</a></li>
            <li><a class="text-muted" href="/lessons">Lessons</a></li>
            <li><a class="text-muted" href="/#About">About</a></li>
          </ul>
        </div>
      </div>
</div>
</footer>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark nav-open-road">
  <a class="navbar-brand" href="#"><%= link_to root_path do %><%= image_tag("1x/logo_1.png", :alt => "Open | Road Driving School") %><% end %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
      <%= link_to "Lessons", lessons_path, class: 'nav-link' %>      
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#about-section">About</a>
      </li>    
      <li class="nav-item">
        <a class="nav-link" href="/account">My Account</a>
      </li> 

      <% if current_user %>
      <li class="nav-item">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      
      </li>
      <% else %>
        
      <li class="nav-item">
      <%= link_to "Register", new_user_registration_path, class: 'nav-link' %>      </li>
      <li class="nav-item">
      <%= link_to "Login", new_user_session_path, class: 'nav-link' %>      </li>
      <% end %>
      </li>
      <% if current_user && current_user.admin? %>%>
      <li class="nav-item">
      <%= link_to  "Admin Panel", admin_index_path, class: 'nav-link', id: 'admin-link' %>      </li>
      <% else %>
      <% if current_user %>
        <div class="cart-text">
              <%= render 'layouts/cart_text' %>
      </div>
      <% end %>
      <% end %>


    </ul>
  </div>  
</nav>


     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open | Road Driving School - Dublin</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://unpkg.com/scrollreveal/dist/scrollreveal.min.js' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'basicstyles' , media: 'all'%>
    <%=  stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css' %>

    <%= favicon_link_tag '1x/open-road.ico' %>
  </head>
  <body>
     <%= render 'layouts/nav_bar' %>
  

  
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_carousel.html.erb
<section id="reviews">
    <div class="container-fluid">
        <h2 class="text-center mb-3 review">Reviews</h2>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner row w-100 mx-auto">
              <div class="carousel-item col-md-4 active">
                  <div class="card review-card">
                  <%= image_tag("1.jpg", :alt => "Open | Road Driving School", class: "card-img-top img-fluid") %>
                    <div class="card-body">
         
                      <p class="card-text">Jim taught me three-point turns when I though I was a lost cause. Can't recommend him enough</p>
                      <footer class="blockquote-footer text-right">Tobi Maguire <cite title="Source Title">Finglas</cite></footer>
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star checked"></span>
                    </div>
                  </div>
                </div>
                <div class="carousel-item col-md-4">
                    <div class="card review-card">
                    <%= image_tag("2.jpg", :alt => "Open | Road Driving School", class: "card-img-top img-fluid") %>
                      <div class="card-body">
                        
                        <p class="card-text">Got my test first time at 45 years of age thanks to Jim's patience and encouragement.</p>
                        <footer class="blockquote-footer text-right">Mary Moore <cite title="Source Title">Phibsboro</cite></footer>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star checked"></span>
                        <span class="fa fa-star"></span>
                      </div>
                    </div>
                  </div>
                  <div class="carousel-item col-md-4">
                      <div class="card review-card">
                                 <%= image_tag("3.jpg", :alt => "Open | Road Driving School", class: "card-img-top img-fluid") %>
                      
                        <div class="card-body">
                      
                          <p class="card-text">Delighted to have gotten my test with Jim's help. He's an absolute gentleman.</p>
                          <footer class="blockquote-footer text-right">John Dunne <cite title="Source Title">Cabra</cite></footer>
                          <span class="fa fa-star checked"></span>
                          <span class="fa fa-star checked"></span>
                          <span class="fa fa-star checked"></span>
                          <span class="fa fa-star checked"></span>
                          <span class="fa fa-star checked"></span>
                        </div>
                      </div>
                    </div>
                    <div class="carousel-item col-md-4">
                        <div class="card review-card">
                                 <%= image_tag("4.jpg", :alt => "Open | Road Driving School", class: "card-img-top img-fluid") %>
                         
                          <div class="card-body">
                     
                            <p class="card-text">I found he has a better way of explaining things than any instructor I've had before. Really nice guy.</p>
                            <footer class="blockquote-footer text-right">Hugh Healy <cite title="Source Title">Marino</cite></footer>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star"></span>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item col-md-4">
                          <div class="card review-card">
                                 <%= image_tag("5.jpg", :alt => "Open | Road Driving School", class: "card-img-top img-fluid") %>
         
                            <div class="card-body">
                   
                              <p class="card-text">Getting my license was the best thing I ever did. I can't believe I put it off for so long. </p>
                              <footer class="blockquote-footer text-right">Malwa Zieba <cite title="Source Title">Drumcondra</cite></footer>
                              <span class="fa fa-star checked"></span>
                              <span class="fa fa-star checked"></span>
                              <span class="fa fa-star checked"></span>
                              <span class="fa fa-star checked"></span>
                              <span class="fa fa-star checked"></span>
                            </div>
                          </div>
                        </div>
                        <div class="carousel-item col-md-4">
                            <div class="card review-card">
                                 <%= image_tag("6.jpg", :alt => "Open | Road Driving School", class: "card-img-top img-fluid") %>
                              <div class="card-body">
                                <p class="card-text">He helped me to conquer the dreaded reverse around a corner. I'm much less scared of them now.</p>
                                <footer class="blockquote-footer text-right">Paul Nolan <cite title="Source Title">Finglas</cite></footer>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                              </div>
                            </div>
                          </div>
          </div>
          <a class="carousel-control-prev icon-carousel" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon icon-carousel" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon icon-carousel" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
        </div>
    
</section>

app/views/pages/_map.html.erb
<%#MAP%>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB8aRaDQTKA_HlpZBtHyJR5O8Nj0aJX-wI"></script>

        <script type="text/javascript">
            // When the window has finished loading create our google map below
            google.maps.event.addDomListener(window, 'load', init);


            function init() {
                // Basic options for a simple Google Map
                // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
                var mapOptions = {
                    // How zoomed in you want the map to start at (always required)
                    zoom: 15,
    
                    // The latitude and longitude to center the map (always required)
                    center: new google.maps.LatLng(53.383756, -6.275776),
    
                    // How you would like to style the map.
                    // This is where you would paste any style found on Snazzy Maps.
                    styles: [{
                        "featureType": "all",
                        "elementType": "labels.text.fill",
                        "stylers": [{
                            "color": "#ffffff"
                        }]
                    }, {
                        "featureType": "all",
                        "elementType": "labels.text.stroke",
                        "stylers": [{
                            "visibility": "off"
                        }]
                    }, {
                        "featureType": "all",
                        "elementType": "labels.icon",
                        "stylers": [{
                            "visibility": "off"
                        }]
                    }, {
                        "featureType": "administrative",
                        "elementType": "geometry.fill",
                        "stylers": [{
    
                            "color": "#ff7417"
    
                        }]
                    }, {
                        "featureType": "administrative",
                        "elementType": "geometry.stroke",
                        "stylers": [{
    
                            "color": "#ff7417"
                        }, {
                            "weight": 1.2
                        }]
                    }, {
                        "featureType": "administrative.locality",
                        "elementType": "geometry.fill",
                        "stylers": [{
                            "lightness": "-1"
                        }]
                    }, {
                        "featureType": "administrative.neighborhood",
                        "elementType": "labels.text.fill",
                        "stylers": [{
                            "lightness": "0"
                        }, {
                            "saturation": "0"
                        }]
                    }, {
                        "featureType": "administrative.neighborhood",
                        "elementType": "labels.text.stroke",
                        "stylers": [{
                            "weight": "0.01"
                        }]
                    }, {
                        "featureType": "administrative.land_parcel",
                        "elementType": "labels.text.stroke",
                        "stylers": [{
                            "weight": "0.01"
                        }]
                    }, {
                        "featureType": "landscape",
                        "elementType": "geometry",
                        "stylers": [{
    
                            "color": "#ff7417"
    
                        }]
                    }, {
                        "featureType": "poi",
                        "elementType": "geometry",
                        "stylers": [{
                            "color": "#ff7417"
    
                        }]
                    }, {
                        "featureType": "road",
                        "elementType": "geometry.stroke",
                        "stylers": [{
                            "visibility": "off"
                        }]
                    }, {
                        "featureType": "road.highway",
                        "elementType": "geometry.fill",
                        "stylers": [{
                            "color": "#BF4E30"
                        }]
                    }, {
                        "featureType": "road.highway.controlled_access",
                        "elementType": "geometry.stroke",
                        "stylers": [{
                            "color": "#BF4E30"
                        }]
                    }, {
                        "featureType": "road.arterial",
                        "elementType": "geometry",
                        "stylers": [{
                            "color": "#BF4E30"
                        }]
                    }, {
                        "featureType": "road.local",
                        "elementType": "geometry",
                        "stylers": [{
                            "color": "#BF4E30"
                        }]
                    }, {
                        "featureType": "transit",
                        "elementType": "geometry",
                        "stylers": [{
                            "color": "#BF4E30"
                        }]
                    }, {
                        "featureType": "water",
                        "elementType": "geometry",
                        "stylers": [{
                            "color": "#324046"
                        }]
                    }]
                };
    

                // Get the HTML DOM element that will contain your map
                // We are using a div with id="map" seen below in the <body>
                var mapElement = document.getElementById('map');
    
                // Create the Google Map using our element and options defined above
                var map = new google.maps.Map(mapElement, mapOptions);
    
                var image = "<%= asset_path '1x/map-car4.png' %>";

                // Let's also add a marker while we're at it
                var carmarker = new google.maps.Marker({
                    position: new google.maps.LatLng(53.383756, -6.275776),
                    animation: google.maps.Animation.DROP,
                    map: map,
                    title: 'Open | Road',
                    icon: image
                });

                // Update map and marker on area click

                 google.maps.event.addDomListener(document.getElementById('1'), 'click', function () {
                    map.setCenter(new google.maps.LatLng(53.383756, -6.275776));
                    carmarker.setPosition(new google.maps.LatLng(53.383756, -6.275776));
                });
                
                 google.maps.event.addDomListener(document.getElementById('2'), 'click', function () {
                    map.setCenter(new google.maps.LatLng(53.364114, -6.257817));
                    carmarker.setPosition(new google.maps.LatLng(53.364114, -6.257817));
                 
                    
                });

                google.maps.event.addDomListener(document.getElementById('3'), 'click', function () {
                    map.setCenter(new google.maps.LatLng(53.391782,-6.298959));
                    carmarker.setPosition(new google.maps.LatLng(53.391782,-6.298959));
                });
            }
        </script>

   
        <%# MAP %>


<section id="address">
  <div class="container-fluid">
    <div class="row d-flex">
       <div class="col-md-4 ml-1"> 
       <h2>Where I work</h2>
        <p>I work around the North Dublin region. My primary areas are Drumcondra, Finglas and Glasnevin. However, I'm flexible and always enjoy the challenge of teaching in new areas.</p>
        <p id="map-customisers"><a href"#" id="1">Glasnevin</a> | <a href"#" id="2">Drumcondra</a> | <a href"#" id="3">Finglas</a></p></div>
               <div class="col-md-4 ml-1"> 
               <div id="map"></div>
               </div>
       
       </div>
</div>

</section>

app/views/pages/account.html.erb
<div class="container-fluid">
<div class="row d-flex justify-content-center">
<section class="form-section col-md-6">
<h2>My Account</h2>
<h3>My lessons</h3>
<div class="lessons-rows">

<% if @lessons.present? %>
 <% @lessons.each_with_index do |i, index| %>
    <p class="faded-lesson"> <%= i.lesson_start.strftime("%d/%m/%Y - %l%P") %></p>
    <hr>
    <% end %>
    <% else %>
    <div id="accordion"></div>
    <p class="sub-head-accord"></p>
        </div>
    <% end %>
  
 
    <h3>My details</h3>
    <p><%= @user.name %> - <%= @user.email %>
    <p><%= link_to "Edit account details", edit_user_registration_path(current_user) %></p>
       </div>
  </section>
</div>
</div>

app/views/pages/home.html.erb
<header>
<div class="jumbotron text-center home-mast">
<div class="container-fluid">
    <%= image_tag("1x/logo-triangle.png", :alt => "Open | Road Driving School", class: "animated lightSpeedIn logo") %>
    <h2>Teaching Glasnevin to drive since 1975</h2> 
    <br />
    <%= button_to "Book a lesson", lessons_path, class: 'btn btn-primary road-submit' %>
  </div>
  </div>
  </header>
 

  <section class="about" id="about-section">
  <div class="container-fluid">
    <div class="text-center">
        <h2 class="display-4 reveal">Hi, I'm Jim</h2>
      </div>
     <div class="row d-flex justify-content-center">
       <div class="col-md-4 ml-1">

         <p class="lead">Born and raised in Glasnevin, I've been teaching people to drive for many years around North Dublin. I firmly believe that everyone can enjoy learning to drive and it's never too late to start learning.</p>
         <p class="lead">I'm flexible in my availability and keen to accomodate anyone who is determined to learn. Driving is a great skill that you'll always be glad you learned. There's nothing like the feeling of passing your driving test.</p>         
         <div class="jim"><%= image_tag("SVG/jimsig.svg", class: 'mt1 reveal', id: 'signature', align: 'right' )%></div>
       </div>
       <div class="col-md-4 ml-1">
       <%= image_tag("jimmy.jpg", :alt => "Jim, Open | Road Founder", class: 'img fluid ml-1', id: 'jimmy' )%>

     </div>
     </div>
    </div>
  </section>
    <%= render 'pages/carousel' %>
        <%= render 'pages/map' %>

<script>

window.sr = ScrollReveal();
sr.reveal('.reveal');
sr.reveal('.jim');
</script>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading road-calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"> <%= start_date.strftime("%a %d %B %Y") %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>