config/routes.rb
Rails.application.routes.draw do
  get 'admin/new'
  get 'admin/index'
  get 'account/', to: 'pages#account'
  resources :availabilities
  resources :lessons
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges
  root to: "pages#home"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end 

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="col-xs-8">
<h4><%= lesson.date_readable %></h4>
<p> <%= lesson.time_readable %> <%= lesson.meeting_point %> </p>
</div>
<div class="col-xs-4">

<%= form_for order_item, remote: true do |f| %>
  <p class="text-right">Price: <span style="color: #ff7417"><%= number_to_currency order_item.unit_price, unit: "€"  %></span> &nbsp;|&nbsp;  <%= link_to "Remove", order_item, { data: { confirm: "Are you sure you wish to delete the lesson '#{order_item.lesson.id}' from your cart?" }, method: :delete, remote: true } %></p>
      <%= f.hidden_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
      <%= f.hidden_field :lesson_id, value: lesson.id %>
    </div>
<% end %>
<hr>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
<hr>
<%= image_tag("1x/parked.png", :alt => "Open | Road Driving School", class: 'animated pulse feature-graphic') %>
  <p class="text-center">
    No items to display.<br /> Please <%= link_to "go back", lessons_path %> and add some items to your cart.
  </p>

<% else %>
  <% @order_items.each do |order_item| %>
    <p class="sub-head-accord">You're almost there!</p>
    <hr>
    <%= render 'carts/cart_row', lesson: order_item.lesson, order_item: order_item %>
  <% end %>
<% end %>

app/views/carts/_totals.html.erb
<div>
  <% if @order_items.size == 0 %>
  <div></div>
  <% else %>
  
<div class="container">
      <div id="cart-subtotal" >
      <p class="text-right"><span class="total">Total</span>&nbsp;&nbsp;<span class="total-amount"><%= number_to_currency current_order.subtotal, unit: "€" %></span></p>
      <%= link_to "Continue to payment", new_charge_path, class: 'btn btn-primary cart-submit' %>
      </div>

    </div>
    <% end %>
  
  </div>

app/views/carts/show.html.erb
<div class="container-fluid">
<div class="row d-flex justify-content-center">
<section class="form-section col-md-4">
<h2>Your Cart</h2>

<div class="shopping-cart">

  <%= render "shopping_cart" %>
</div>
<div class="total-text">
<%= render "totals" %><br /><br />
 </div>
  </section>
</div>
</div>