config/routes.rb
Rails.application.routes.draw do
  get 'admin/new'
  get 'admin/index'
  get 'account/', to: 'pages#account'
  resources :availabilities
  resources :lessons
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges
  root to: "pages#home"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
    enum bookable: [:available, :unavailable]
    has_many :order_items
    validates :start_time, uniqueness: true
    
    after_initialize :set_default_bookable, :if => :new_record?

    def set_default_bookable
        self.bookable ||= :available
      end

    def date_readable
        start_time.strftime("%d/%m/%Y")
    end 

    def time_readable
        start_time.strftime("%l%P")
    end 

    def datetime_readable
        date_readable + " " + time_readable
    end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @lessons = Lesson.available
    @lesson_count = Lesson.available.count
    @order_item = current_order.order_items.new
    
  end

  def new
    @lesson = Lesson.new
  end 

  def create
    @lesson = Lesson.new(lesson_params)
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end 
    end

    def booked
      @lesson = Lesson.find(params[:id])
      @lesson.unavailable!
    end 

    def edit
      @lesson = Lesson.find(params[:id])
    end 

    def update
      @lesson = Lesson.find(params[:id])
      respond_to do |format|
          if @lesson.update(params.require(:portfolio).permit(:title, :subtitle, :body))
            format.html { redirect_to @lesson, notice: 'Record was successfully updated.' }
            format.json { render :index, status: :ok, location: @lesson }
          else
            format.html { render :edit }
            format.json { render json: @lesson.errors, status: :unprocessable_entity }
          end
        end
    end 
 
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
    
   end 

  def show
    @lesson = Lesson.find(params[:id])
    @order_item = current_order.order_items.new
  end 

  private
  def lesson_params
    params.require(:lesson).permit(:id, :duration, :price, :meeting_point, :date, :start_time)
  end  

end

app/helpers/lessons_helper.rb
module LessonsHelper

end

app/views/lessons/_lesson_row.html.erb
    <% lessons.each do |lesson| %>
     <% if current_user && current_user.admin? %>
      <p><span class="lesson-time"><%= lesson.time_readable %></span>  <%= link_to 'Remove', lesson_path(lesson), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary lesson-update' %></p>
  </div>
      <% else %>
      <%= form_for (@order_item), remote: true do |f| %>
    <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
    <%= f.hidden_field :lesson_id, value: i.id %>
  <p><span class="lesson-time"><%= lesson.time_readable %></span><%= f.submit "Add to Cart", class: 'btn btn-primary lesson-update',  method: :create, remote: true %></p>
  <% end %>
  </div>
  <% end %>
  <hr class="lesson-line">
  <% end %>

app/views/lessons/create.html.erb
<h1>Lessons#create</h1>
<p>Find me in app/views/lessons/create.html.erb</p>

app/views/lessons/destroy.js.erb
$(".lessons-rows").html("<%= escape_javascript(render 'availabilities/new_lesson_row') %>")

app/views/lessons/index.html.erb
<div class="container-fluid">
<div class="row d-flex justify-content-center">
<section class="form-section col-md-6">
<h2>Pick a lesson</h2>
<p class="sub-head-accord">Choose a driving lesson from the list below.<br />Lessons are charged at a flat rate of €35 per hour.</p>
<hr>
<div class="lesson-row">
<% if @lessons.present? %>
<%= calendar number_of_days: 1, events: @lessons do |date, lessons| %>
  <div class="admin-row">
  <% lessons.each_with_index do |i, index| %>
     <% if current_user && current_user.admin? %>
      <p><span class="lesson-time"><%= i.time_readable %></span>  <%= link_to 'Remove', lesson_path(i), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary lesson-update' %></p>
    
  </div>
      <% else %>
      <%= form_for (@order_item), remote: true do |f| %>
    <%= f.hidden_field :quantity, value: 1, class: "form-control", min: 1 %>
    <%= f.hidden_field :lesson_id, value: i.id %>
  <p><span class="lesson-time"><%= i.time_readable %></span><%= f.submit "Add to Cart", class: 'btn btn-primary lesson-update',  method: :create, remote: true %></p>
  <% end %>
<% end %>

  </div>
  <hr class="lesson-line">
    <% end %>
<% end %>
<% end %>


</div>
  </section>
</div>
</div>

app/views/lessons/show.html.erb
<div class="container-fluid">
<div class="row d-flex justify-content-center">
<section class="form-section">
  <div class="container">
<h2>Lesson Summary</h2>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
      <%= render "lesson_row", lesson: @lesson, order_item: @order_item %>
   
  </div>

  </div>
  </div>
  </section>
</div>
</div>

app/views/lessons/update.html.erb
<h1>Lessons#update</h1>
<p>Find me in app/views/lessons/update.html.erb</p>